<a href="https://colab.research.google.com/github/aorko01/2.Learning_pytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
#scaler,vecor and matrix all are encoded as tensor
#so for using any of these we would be using tensor
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

7

In [ ]:
vector =  torch.tensor([[7,7],[9,0]])
vector

tensor([[7, 7],
        [9, 0]])

In [ ]:
vector.ndim

2

In [ ]:
Matrix =torch.tensor([[7,8],
                      [9,10]])

In [ ]:
#This returns the row number
Matrix.ndim

2

In [ ]:
#This returns the total shape
Matrix.shape

In [ ]:
#tensor with random numbers
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5702, 0.5358, 0.6465, 0.3206],
        [0.2928, 0.2504, 0.9597, 0.5551],
        [0.4173, 0.8629, 0.2964, 0.7213]])

In [ ]:
#parameters required for tensors
#1st the tensor itself
#2nd the type of data that the tensor holds
#3rd the device that the tensor is going to run on
#   If one tensor lives on the gpu and the other tensor lives on the cpu then it would show error
#4th to keep track of the gradients
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=torch.float16,
                              device=None,
                              requires_grad=False)

float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
#change the tensor datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
tensor_1 = torch.tensor([[1,2,3],
                       [4,5,6]])

tensor_2 = torch.tensor([[1,2,3],
                       [4,5,6]])

#this would give dimernsion errors
# torch.matmul(tensor_1,tensor_2)

#corrected code with corrected dimension with transpose for the multiplication
#.T basically transposes the matrix
torch.matmul(tensor_1,tensor_2.T)

tensor([[14, 32],
        [32, 77]])

In [51]:
x=torch.arange(1.0,10.0)
x,x.shape

#the following line would give an error because the input numebrs are incompatible with the shape I am asking
#so while reshaping it is important to use a shape that is compatible with the input
# x_reshaped=x.reshape(1,7)
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [55]:
#view does almost the same as reshape but
#while reshape copies the things into new memory location but
#view shares the same memory location
z=x.view(1,9)
z
z[:,0]=5
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])